server:
  port: 9052

feign:
  client:
    config:
      mt-core-service:
        url: http://localhost:9050/api/v1
        connectTimeout: 5000
        readTimeout: 5000

mt-middle:
  core-service-url: ${feign.client.config.mt-core-service.url}
  endpoints:
    transaction: ${mt-middle.core-service-url}/transaction
    accounts: ${mt-middle.core-service-url}/accounts
    reports: ${mt-middle.core-service-url}/reports
    category: ${mt-middle.core-service-url}/category
    auth: ${mt-middle.core-service-url}/auth
